# Generated by Django 4.2.3 on 2023-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=250)),
                ("preview", models.ImageField(blank=True, upload_to="blog")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("published", models.BooleanField()),
                ("views_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
                "ordering": ["-created_at"],
            },
        ),
    ]
