# Generated by Django 4.2.3 on 2023-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogentry_slug_alter_blogentry_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
    ]
