# Generated by Django 4.2.3 on 2023-07-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 11, 39, 51, 350280, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
