# Generated by Django 4.2.3 on 2023-07-29 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="is_active",
            new_name="active",
        ),
    ]
