# Generated by Django 4.2.3 on 2023-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [("set_published", "Can publish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
